# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4654e5e5b37bb50c13336a2a9324fcb6aaca5b167d2cc7865ead6dd995e6118b80c25fcc57566cb2dae8792cc54df3c643a63604d2eb4b90a596dd09990a87c7

test:
  secret_key_base: 5cf4452a69aa455ae32b5602bfbb933446b7167ee8c4b2fcacee71a075e8b759cddd28a2dc31e5a979372cb3fe201ff7e6cf42e8c087adb141ee9ced94656593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e5b4ad1b7d5aa9d0d58256e3e010f1e6092b9f684309984fadb08758ef2fdc97562b3d0e027aac2c8fe23178eb75701b26e8bbf5663ca9a9a3909488b526c4e4
